FROM debian:bookworm-slim
LABEL maintainer="kolohals"
LABEL description="recollsearch"
ARG DATADIR=/data
ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL="C.UTF-8"
ARG UNAME=recolluser
ARG UID=1000
ARG GID=1000

RUN groupadd -g $GID -o $UNAME && \
    useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME

COPY recoll.conf /home/$UNAME/.recoll/recoll.conf

# Recoll do próprio Debian bookworm + dependências
RUN apt-get update -yq && \
    apt-get install -yq --no-install-recommends \
        python3 python3-setuptools python3-waitress python3-bottle \
        recollcmd python3-recoll \
        git ca-certificates \
        poppler-utils \
        unrtf antiword wv \
        unzip libimage-exiftool-perl \
        aspell-pt-br aspell-en \
        python3-mutagen python3-lxml

# WebUI (removendo o bottle.py embutido, incompatível com Python 3.11)
RUN mkdir -p $DATADIR && \
    cd / && \
    git clone https://github.com/ameisehaufen/kmrecollwebui.git recollwebui && \
    rm -f /recollwebui/bottle.py && \
    rm -rf /recollwebui/.git

# Limpeza
RUN apt-get remove -yq git && \
    apt-get autoremove -yq && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN chown -R $UID:$GID /home/$UNAME/.recoll

ENV RECOLL_CONFDIR=/home/$UNAME/.recoll
ENV RECOLL_INDEX_DIR=$DATADIR
VOLUME $DATADIR
VOLUME /home/$UNAME/.recoll
EXPOSE 8080

USER $UNAME
CMD ["/usr/bin/python3", "/recollwebui/webui-standalone.py", "-a", "0.0.0.0"]
